/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhtd.view;

import com.thanhtd.controller.DbController;
import com.thanhtd.model.CauHoi;
import java.util.List;
import java.util.TreeMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author Thanh Tran
 */
public class ChooseSubjectTestForTeacherDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChooseSubjectTestForTeacherDialog
     */
    DefaultListModel dlm = new DefaultListModel();
    TreeMap<String, Integer> listSubjectExam = null;

    public ChooseSubjectTestForTeacherDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        createAndShowUI();
    }

    private void createAndShowUI() {
        setTitle("Choose General Test");
        setLocationRelativeTo(null);

        for (String i : DbController.getListGeneralExamId()) {
            jComboBox1.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        listSubjectExam = DbController.GetListSubjectExamId(jComboBox1.getSelectedItem().toString());
        if (!dlm.isEmpty()) {
            dlm.clear();
        }
        for (String i : listSubjectExam.keySet()) {
            dlm.addElement(i);
        }
        jList1.setModel(dlm);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
            List<CauHoi> listCauHoi = null;
            BeginTestDialog beginTest = null;
            switch (jList1.getSelectedValue()) {
                case "Math":
                    listCauHoi = DbController.getListQuestionOfMathTest(listSubjectExam.get(jList1.getSelectedValue()));
                    beginTest = new BeginTestDialog(null, true, listCauHoi);
                    beginTest.getContentPane();
                    beginTest.setVisible(true);
                    if (beginTest.getFinished()) {
                        dlm.removeElement("Math");
                        jList1.setModel(dlm);
                    }
                    break;
                case "Literature":
                    listCauHoi = DbController.getListQuestionOfLiteratureTest(listSubjectExam.get(jList1.getSelectedValue()));
                    beginTest = new BeginTestDialog(null, true, listCauHoi);
                    beginTest.getContentPane();
                    beginTest.setVisible(true);
                    if (beginTest.getFinished()) {
                        dlm.removeElement("Literature");
                        jList1.setModel(dlm);
                    }
                    break;
                case "History":
                    listCauHoi = DbController.getListQuestionOfHistoryTest(listSubjectExam.get(jList1.getSelectedValue()));
                    beginTest = new BeginTestDialog(null, true, listCauHoi);
                    beginTest.getContentPane();
                    beginTest.setVisible(true);
                    if (beginTest.getFinished()) {
                        dlm.removeElement("History");
                        jList1.setModel(dlm);
                    }
                    break;
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
